Output a syslog message when gf* command fails or it outputs no data.

diff --git a/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_cli.sh.in b/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_cli.sh.in
--- a/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_cli.sh.in
+++ b/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_cli.sh.in
@@ -1,27 +1,38 @@
 #!/bin/sh
 
-# defines
-CONF_FILE=@ZABBIX_EXTSCRIPTDIR@/zbx_chk_gfarm.conf
+. @ZABBIX_EXTSCRIPTDIR@/zbx_gfarm_utils.inc
 
-# check config file
-if [ -f $CONF_FILE ]; then
-    . $CONF_FILE
-else
-    echo -1
+# read a configuration file
+CONF_FILE=@ZABBIX_EXTSCRIPTDIR@/zbx_chk_gfarm.conf
+[ -f $CONF_FILE ] && . $CONF_FILE
+
+# create temporary files
+outfile=/tmp/zbx_chk_gfhost_cli.$$
+errfile=/tmp/zbx_chk_gfhost_cli.$$.err
+trap "rm -f $outfile $errfile; exit 1" 1 2 3 15
+rm -f $outfile $errfile
+
+# execute 'gfhost'
+GFCMD="gfhost $*"
+$GFCMD > $outfile 2> $errfile
+GFCMD_EXITCODE=$?
+if [ $GFCMD_EXITCODE -ne 0 ]; then
+    echo "error: '$GFCMD' error."
+    log_err "'$GFCMD' failed with the exit code $GFCMD_EXITCODE"
+    rm -f $outfile $errfile
     exit 0
 fi
 
-# exec check command
-RESULT=`gfhost $*`
-
-if [ $? != 0 ]; then
-    RESULT="error: gfhost $* error."
-else
-    if [ -z "${RESULT}" ]; then
-        RESULT="error: gfhost show no fsn."
-    fi
+# check whether 'gfhost' outputs results correctly.
+if [ ! -s $outfile ]; then
+    log_warning "'$GFCMD' outputs no data"
+    [ -s $errfile ] && head -1 $errfile | syslog_warning
+    rm -f $outfile $errfile
+    exit 0
 fi
 
-echo $RESULT
+# print the results.
+cat $outfile
+rm -f $outfile $errfile
 
 exit 0
