gfarm-zabbix supports multiple Gfarm servers runinng on the same node (#684).

diff --git a/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_gfsd.sh.in b/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_gfsd.sh.in
--- a/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_gfsd.sh.in
+++ b/gfarm_zabbix/trunk/src/gfarm-zabbix_scripts/externalscripts/zbx_chk_gfhost_gfsd.sh.in
@@ -1,31 +1,37 @@
 #!/bin/sh
 
+. @ZABBIX_EXTSCRIPTDIR@/zbx_gfarm_utils.inc
+
 # defines
 CONF_FILE=@ZABBIX_EXTSCRIPTDIR@/zbx_chk_gfarm.conf
 
 # check config file
-if [ -f $CONF_FILE ];
-    then
+if [ -f $CONF_FILE ]; then
     . $CONF_FILE
 else
-    echo  -1;
-    exit 0;
+    echo -1
+    exit 0
 fi
 
-# exec check command
-if [ X"$MY_HOST" != X ]; then
-    FSN_NAME=$MY_HOST
-else
-    FSN_NAME=`hostname`
+# create the temporary file
+tmpfile=`mktemp`
+trap "rm -f $tmpfile >/dev/null 2>&1" EXIT
+
+gfhost_options="-l"
+
+gfhost ${gfhost_options} > $tmpfile
+if [ $? != 0 ]; then
+    echo "error: gfhost ${gfhost_options} error."
+    exit 0
 fi
 
-RESULT=`gfhost $* | grep $FSN_NAME`
-
-if [ $? != 0 ];
-then
-    RESULT="gfhost $* error."
-fi
-
-echo $RESULT
+while read prefix gfsdhost port listen_aadress; do
+    grep ${gfsdhost} $tmpfile
+    if [ $? -ne 0 ]; then
+        echo "error: gfsd on ${gfsdhost} is not shown on gfhost output"
+    fi
+done<<EOF
+`parse_gfsd_confs "$1"`
+EOF
 
 exit 0
