regen

diff --git a/gfarm_gridftp_dsi/trunk/configure b/gfarm_gridftp_dsi/trunk/configure
--- a/gfarm_gridftp_dsi/trunk/configure
+++ b/gfarm_gridftp_dsi/trunk/configure
@@ -2281,8 +2281,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 ### --with-gfarm=GFARM
-echo "$as_me:$LINENO: checking Gfarm file system package" >&5
-echo $ECHO_N "checking Gfarm file system package... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for Gfarm file system" >&5
+echo $ECHO_N "checking for Gfarm file system... $ECHO_C" >&6
 
 # Check whether --with-gfarm or --without-gfarm was given.
 if test "${with_gfarm+set}" = set; then
@@ -2314,8 +2314,8 @@ else
 fi;
 
 ### --with-globus=GLOBUS_LOCATION
-echo "$as_me:$LINENO: checking Globus toolkit" >&5
-echo $ECHO_N "checking Globus toolkit... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for Globus toolkit" >&5
+echo $ECHO_N "checking for Globus toolkit... $ECHO_C" >&6
 
 # Check whether --with-globus or --without-globus was given.
 if test "${with_globus+set}" = set; then
@@ -2327,8 +2327,10 @@ case x$with_globus in
   *) GLOBUS_LOCATION=$with_globus ;;
 esac
 if test x"$GLOBUS_LOCATION" = x; then
-  { { echo "$as_me:$LINENO: error: GLOBUS_LOCATION is not specified.  Use --with-globus option." >&5
-echo "$as_me: error: GLOBUS_LOCATION is not specified.  Use --with-globus option." >&2;}
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: Specify GLOBUS_LOCATION using --with-globus option" >&5
+echo "$as_me: error: Specify GLOBUS_LOCATION using --with-globus option" >&2;}
    { (exit 1); exit 1; }; }
 fi
 echo "$as_me:$LINENO: result: $GLOBUS_LOCATION" >&5
@@ -2336,30 +2338,37 @@ echo "${ECHO_T}$GLOBUS_LOCATION" >&6
 
 
 # guess FLAVOR
-FTPSERVER=${GLOBUS_LOCATION}/sbin/globus-gridftp-server
-if test ! -f $FTPSERVER; then
-  { { echo "$as_me:$LINENO: error: $FTPSERVER is not found" >&5
-echo "$as_me: error: $FTPSERVER is not found" >&2;}
-   { (exit 1); exit 1; }; }
+echo "$as_me:$LINENO: checking for Globus flavor" >&5
+echo $ECHO_N "checking for Globus flavor... $ECHO_C" >&6
+if test x"$FLAVOR" = x; then
+  FTPSERVER=$GLOBUS_LOCATION/sbin/globus-gridftp-server
+  FLAVOR=`ldd $FTPSERVER | $AWK '($1 ~ /^libglobus_gridftp_server_control_/){name=gensub(/^libglobus_gridftp_server_control_(.+)\.so.*/,"\\\\1","g",$1);print name}'`
 fi
 if test x"$FLAVOR" = x; then
-    FLAVOR=`ldd ${FTPSERVER} | $AWK '($1 ~ /^libglobus_gridftp_server_control_/){name=gensub(/^libglobus_gridftp_server_control_(.+)\.so.*/,"\\\\1","g",$1);print name}'`
-fi
-if test x"$FLAVOR" = x; then
-    { { echo "$as_me:$LINENO: error: Specify Globus flavor with --with-globus-flavor option" >&5
-echo "$as_me: error: Specify Globus flavor with --with-globus-flavor option" >&2;}
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: Specify Globus flavor using --with-globus-flavor option" >&5
+echo "$as_me: error: Specify Globus flavor using --with-globus-flavor option" >&2;}
    { (exit 1); exit 1; }; }
 fi
+echo "$as_me:$LINENO: result: $FLAVOR" >&5
+echo "${ECHO_T}$FLAVOR" >&6
 
 
 # make sure nonthreaded gridftp server is installed
-f_prefix=`expr "${FLAVOR}" : '\(.*\)pthr'`
-f_pthr=`expr "${FLAVOR}" : '.*\(pthr\)'`
+echo "$as_me:$LINENO: checking whether nonthreaded GridFTP server is installed" >&5
+echo $ECHO_N "checking whether nonthreaded GridFTP server is installed... $ECHO_C" >&6
+f_prefix=`expr "$FLAVOR" : '\(.*\)pthr'`
+f_pthr=`expr "$FLAVOR" : '.*\(pthr\)'`
 if test x"$f_pthr" = xpthr; then
-  { { echo "$as_me:$LINENO: error: Copy ${GLOBUS_LOCATION}/sbin/${f_prefix}/shared/globus-gridftp-server into ${GLOBUS_LOCATION}/sbin/globus-gridftp-server" >&5
-echo "$as_me: error: Copy ${GLOBUS_LOCATION}/sbin/${f_prefix}/shared/globus-gridftp-server into ${GLOBUS_LOCATION}/sbin/globus-gridftp-server" >&2;}
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  { { echo "$as_me:$LINENO: error: Copy $GLOBUS_LOCATION/sbin/$f_prefix/shared/globus-gridftp-server to $GLOBUS_LOCATION/sbin/globus-gridftp-server" >&5
+echo "$as_me: error: Copy $GLOBUS_LOCATION/sbin/$f_prefix/shared/globus-gridftp-server to $GLOBUS_LOCATION/sbin/globus-gridftp-server" >&2;}
    { (exit 1); exit 1; }; }
 fi
+echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 
 # Checks for libraries.
 
