Brush up test scripts for testing #684 (gfarm-zabbix monitors multiple Gfarm servers runinng on the same node) and #685 (More robust failover script for gfarm-zabbix).

diff --git a/gfarm_zabbix/trunk/src/failure_test_scripts/FT-config b/gfarm_zabbix/trunk/src/failure_test_scripts/FT-config
--- a/gfarm_zabbix/trunk/src/failure_test_scripts/FT-config
+++ b/gfarm_zabbix/trunk/src/failure_test_scripts/FT-config
@@ -2,7 +2,7 @@
 
 . ./FT-common
 
-$gfservice config-gfarm-master gfmd1
+$gfservice -k config-gfarm-master gfmd1
 
 #
 # Configure gfmd servers.
@@ -57,4 +57,49 @@ while [ "X`eval echo \\$gfmd$I`" != X ]; do
 done
 
 rm -f $TMP_GFMD_CONF $TMP_PGPASS
+
+#
+# Create zbx_failover.conf.
+#
+FAILOVER_CONF_DIR=/etc/zabbix/externalscripts
+FAILOVER_CONF_FILE=zbx_failover.conf
+rm -f $FAILOVER_CONF_FILE
+
+(
+	echo "#"
+	echo "# This file is created by FT-config."
+	echo "#"
+
+	I=1
+	while [ "X`eval echo \\$gfmd$I`" != X ]; do
+		echo "[gfmd$I]"
+		echo "host=`$gfservice get-config-gfarm-param \
+			gfmd$I BACKEND_HOSTNAME`"
+		echo "gfmd_listen_port=`$gfservice get-config-gfarm-param \
+			gfmd$I GFMD_PORT`"
+		echo "gfmd_pid_file=`$gfservice get-config-gfarm-param \
+			gfmd$I GFMD_PID_FILE`"
+		echo "gfmd_journal_file=`$gfservice get-config-gfarm-param \
+			gfmd$I METADATA_JOURNAL_DIR`/0000000000.gmj"
+		[ "X`eval echo \\$gfmd${I}_GFBINDIR`" != X ] && \
+			echo "gfarm_bindir=`eval echo \\$gfmd${I}_GFBINDIR`"
+		[ "X`eval echo \\$gfmd${I}_SSH`" != X ] && \
+			echo "ssh=`eval echo \\$gfmd${I}_SSH`"
+		[ "X`eval echo \\$gfmd${I}_SUDO`" != X ] && \
+			echo "sudo=`eval echo \\$gfmd${I}_SUDO`"
+		echo
+		I=`expr $I + 1`
+	done
+) > $FAILOVER_CONF_FILE
+
+if cmp -s $FAILOVER_CONF_DIR/$FAILOVER_CONF_FILE $FAILOVER_CONF_FILE; then
+	true
+else
+	(
+		echo "The file '$FAILOVER_CONF_FILE' might have to be updated"
+		echo "To update it, type the following command:"
+		echo "   cp $FAILOVER_CONF_FILE $FAILOVER_CONF_DIR/$FAILOVER_CONF_FILE"
+	) 1>&2
+fi
+
 exit 0
